### ISSUE TITLE
R is missing for aar projects

### ISSUE THREAD

**Issue by taig** [zbsz/robotest#5]
I can't manage to access the `R` class in an aar project.

```
[error] ./robotest/example/src/test/scala/org.robotest/ResourcesSpec.scala:11: not found: value R
[error]     Robolectric.application.getResources.getString(R.string.test_string) shouldEqual "test"
[error]                                                    ^
[error] one error found
[error] (test:compile) Compilation failed
[error] Total time: 8 s, completed 13.06.2015 19:27:48
```

To reproduce replace `android.Plugin.androidBuild` in `./example/build.sbt` with `android.Plugin.androidBuildAar`. Please note that I did only manage to test this on 0.7 with Robolectric 2.4.

**Comment by zbsz** [comment]
This is a bug of android plugin, it doesn't include R.class in test classpath, it uses generated classes.jar (which doesn't include generated R, because it is not packaged in aar).
Robotest was meant to be regular library (not sbt plugin), so it doesn't know anything about project setup and we can not use classes which are not on classpath. 
We may need to change that somehow to handle resources from dependent aars (issue #4), but in this case I would say R class should be added to test classpath by android plugin.

**Comment by taig** [comment]
Interesting, thank you very much for clarification!
